# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:22.12-alpine AS builder

# Copy the source code and package files
COPY src /app/src
COPY package.json package-lock.json tsconfig.json /app/

WORKDIR /app

# Install dependencies
RUN --mount=type=cache,target=/root/.npm npm install --ignore-scripts

# Build the TypeScript project
RUN npm run build

FROM node:22-alpine AS release

WORKDIR /app

# Copy the build output and package files
COPY --from=builder /app/dist /app/dist
COPY --from=builder /app/package.json /app/package-lock.json /app/

ENV NODE_ENV=production

# Install only production dependencies
RUN npm ci --ignore-scripts --omit=dev

# Set environment variables (to be replaced with actual values)
ENV COINBASE_CDP_API_KEY_NAME=your_api_key_name
ENV COINBASE_CDP_PRIVATE_KEY=your_private_key

# Define the entrypoint
ENTRYPOINT ["node", "dist/index.js"]
